---
resource_types:
  - name: cron-resource
    type: docker-image
    source:
      repository: cftoolsmiths/cron-resource

resources:
  - name: git-dev
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/govuk-shielded-vulnerable-people-service
      branch: feature/794/gatling-in-concourse

  - name: trigger-at-1am
    type: cron-resource
    source:
      expression: "26 16 * * *"
      location: "Local"
      fire_immediately: true

jobs:
  - name: update-pipeline
    serial: true
    plan:
      - get: git-dev
        trigger: true
      - set_pipeline: wip-svp-with-gatling
        file: git-dev/concourse_dev/pipeline.yml

  - name: gatling-workflow-load-test
    plan:
      - get: git-dev
      - get: trigger-at-1am
        trigger: true
      - task: gatling
        file: git-dev/concourse_dev/tasks/gatling-workflow-load-test.yml

  - name: run-daily-and-mi-workflows-in-staging
    plan:
      - get: git-dev
      - get: trigger-at-1am
        trigger: true
      - task: get-aws-credentials
        file: git-dev/concourse_dev/tasks/get-gatling-tester-aws-creds.yml
        params:
          ACCOUNT_ID: 375282846305
          ENVIRONMENT: staging
          REGION: eu-west-2
          DURATION: 21600
      - task: run-pipelines
        config:
          platform: linux
          image_resource:
          type: registry-image
          source:
            repository: governmentpaas/awscli
            tag: latest
          inputs:
            - name: aws-credentials
          run:
            path: ash
            args:
              - -c
              - |
                set -euo pipefail
                source aws-credentials/.env
                aws glue start-workflow-run \
                  --name "cv-vulnerable-people-daily-wave-two-pipeline-staging"
                aws glue start-workflow-run \
                  --name "wave2-mvp-reporting-data-daily-pipeline-staging"
