version: '3'

services:
  chrome-driver:
    image: gdscyber/concourse-chrome-driver:1.1
    volumes:
      - ./behave:/usr/src/app
    command: bash
    environment:
      WEB_APP_BASE_URL: http://webform:5000
      POSTCODE_TIER_OVERRIDE: '{"TE22RR" : {"tier": 2, "shielding": 0}, "TE33RR": {"tier": 3, "shielding": 0 }, "TE44RR": {"tier": 4, "shielding": 1}, "TS33RR": {"tier": 3, "shielding": 1}}'
      NHS_BASE_URL: https://access.sandpit.signin.nhs.uk
      NHS_EMAIL: 
      NHS_PASSWORD: 
      NHS_OTP: 
    ports:
      - "8081:8081"
    links:
      - "webform"
  webform:
    build: 
      dockerfile: Dockerfile
      context: .  
    ports:
      - "5000:5000"
    links:
      - "rds-client-api"
      - "ons-test"
      - "sqs-client-api"
    volumes:
      - .:/app
  ons-test:
    build: 
      dockerfile: Dockerfile
      context: tests/ons-mock
    ports:
      - "8000:8000"
  coronavirus-mysql-pytest:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: coronavirus
    ports:
      - "3306:3306"
  rds-client-api:
    image: koxudaxi/local-data-api
    restart: always
    links:
      - "coronavirus-mysql-pytest"
    environment:
      MYSQL_HOST: coronavirus-mysql-pytest
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      RESOURCE_ARN: 'arn:aws:rds:eu-west-2:123456789012:cluster:dummy'
      SECRET_ARN: 'arn:aws:secretsmanager:eu-west-2:123456789012:secret:dummy'
    ports:
      - "8080:80"
  sqs-client-api:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=eu-west-2
    volumes:
      - ./scripts/create-sqs-queue.sh:/docker-entrypoint-initaws.d/create-sqs-queue.sh
