#========================================================================================
# This Dockerfile creates a container image which contains python 3.8 and google chrome,
# as well as the application source and bundled dependencies.
#
# This is needed for running the feature tests in a container environment like concourse.
#========================================================================================
FROM python:3.8-slim-buster


ENTRYPOINT ["/bin/bash"]
