---
resource_types:
  - name: slack-alert
    type: registry-image
    source:
      repository: arbourd/concourse-slack-alert-resource
      username: ((docker_hub_username))
      password: ((docker_hub_password))

  - name: cron-resource
    type: docker-image
    source:
      repository: cftoolsmiths/cron-resource
      username: ((docker_hub_username))
      password: ((docker_hub_password))

resources:
  - name: git-master
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/govuk-shielded-vulnerable-people-service
      branch: master

  - name: git-sandbox
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/govuk-shielded-vulnerable-people-service
      branch: master

  - name: slack
    type: slack-alert
    source:
      url: ((slack_hook_automate))
      channel: covid-engineering-team
      username: ((readonly_team_name))
      password: ((readonly_local_user_password))

  - name: every-2m
    type: time
    source:
      interval: 2m

  - name: trigger-at-1am
    type: cron-resource
    source:
      expression: "0 1 * * *"
      location: "Local"

  - name: trigger-at-6am
    type: cron-resource
    source:
      expression: "0 6 * * *"
      location: "Local"

# Anchors for later
slack_alert_on_failure: &slack_alert_on_failure
  put: slack
  params:
    alert_type: failed

slack_alert_on_success: &slack_alert_on_success
  put: slack
  params:
    alert_type: success

slack_alert_on_fixed: &slack_alert_on_fixed
  put: slack
  params:
    alert_type: fixed

jobs:
  - name: update-pipeline
    serial: true
    plan:
      - get: git-master
        trigger: true
      - set_pipeline: svp-form
        file: git-master/concourse/pipeline.yml
      - get: git-sandbox
    on_failure: *slack_alert_on_failure
    on_success: *slack_alert_on_fixed

  - name: test
    serial: true
    plan:
      - get: git-master
        trigger: true
        passed: [update-pipeline]
      - task: test
        file: git-master/concourse/tasks/test.yml
    on_failure: *slack_alert_on_failure
    on_success: *slack_alert_on_fixed

  - name: test-sandbox
    serial: true
    plan:
      - get: git-sandbox
        trigger: true
      - get: git-master
        trigger: true
      - task: test
        file: git-master/concourse/tasks/test.yml
    on_failure: *slack_alert_on_failure


  - name: deploy-to-sandbox
    serial: true
    plan:
      - get: git-master
        trigger: true
        passed: [test-sandbox]
      - get: git-sandbox
        trigger: true
        passed: [test-sandbox]
      - task: deploy-to-paas
        config:
        file: git-master/concourse/tasks/deploy-to-govuk-sandbox.yml
        params:
          CF_SPACE: sandbox
          INSTANCES: 2
          CF_STARTUP_TIMEOUT: 5 # minutes
          HOSTNAME: gds-shielded-vulnerable-people-service-sandbox
          SECRET_KEY: ((svp-form/flask-secret-key-base-stg))
          NHS_OIDC_AUTHORITY_URL: https://auth.aos.signin.nhs.uk
          NHS_OIDC_LOGIN_CALLBACK_URL: https://gds-shielded-vulnerable-people-service-sandbox.london.cloudapps.digital/nhs-login-callback
          NHS_OIDC_REGISTRATION_CALLBACK_URL: https://gds-shielded-vulnerable-people-service-sandbox.london.cloudapps.digital/nhs-registration-callback
          NHS_OIDC_CLIENT_ID: gds-svp
          AWS_ACCESS_KEY: ((svp-form/aws-access-key-id-stg))
          AWS_SECRET_ACCESS_KEY: ((svp-form/aws-secret-access-key-stg))
          AWS_SQS_QUEUE_URL: ((svp-form/aws-sqs-queue-url-stg))
          NHS_OIDC_LOGIN_PRIVATE_KEY: ((svp-form/nhs-login-private-key-stg))
          SENTRY_DSN: ((svp-form/sentry-dns-stg))
          GA_TRACKING_ID: UA-43115970-1
          GA_CROSS_DOMAIN_ID: UA-145652997-7
          ENVIRONMENT: SANDBOX
          POSTCODE_TIER_OVERRIDE: ((svp-form/postcode-tier-override))
          SUBMISSION_TRACING_PEPPER: ((submission-tracing-pepper-sandbox))

  - name: smoke-test-sandbox
    serial: true
    plan:
      - get: git-sandbox
        trigger: true
        passed: [deploy-to-sandbox]
      - task: smoke-test
        file: git-sandbox/concourse/tasks/smoke-test-sandbox.yml
        params:
          WEB_APP_BASE_URL: "https://gds-shielded-vulnerable-people-service-sandbox.london.cloudapps.digital"
          MESSAGE: "Checks that the application deployed to sandbox is not serving HTTP error codes"
          POSTCODE_TIER_OVERRIDE: ((svp-form/postcode-tier-override))
          NHS_BASE_URL: https://access.aos.signin.nhs.uk
          NHS_EMAIL: ((svp-form/nhs-email-stg))
          NHS_OTP: ((svp-form/nhs-otp-stg))
          NHS_PASSWORD: ((svp-form/nhs-password-stg))

  - name: e2e-test-sandbox
    serial: true
    plan:
      - get: git-sandbox
        trigger: true
        passed: [smoke-test-sandbox]
      - task: e2e-test
        file: git-sandbox/concourse/tasks/e2e-test-sandbox.yml
        attempts: 2
        params:
          CF_SPACE: "sandbox"
          ENVIRONMENT: "sandbox"
          WEB_APP_BASE_URL: "https://gds-shielded-vulnerable-people-service-sandbox.london.cloudapps.digital"
          MESSAGE: "Checks that the application deployed to sandbox is not serving HTTP error codes"
          POSTCODE_TIER_OVERRIDE: ((svp-form/postcode-tier-override))
          NHS_BASE_URL: https://access.aos.signin.nhs.uk
          NHS_EMAIL: ((svp-form/nhs-email-stg))
          NHS_OTP: ((svp-form/nhs-otp-stg))
          NHS_PASSWORD: ((svp-form/nhs-password-stg))

  - name: deploy-to-staging
    serial: true
    plan:
      - get: git-master
        trigger: true
        passed: [test]
      - task: deploy-to-paas
        config:
        file: git-master/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          CF_SPACE: staging
          INSTANCES: 20
          CF_STARTUP_TIMEOUT: 10 # minutes
          HOSTNAME: gds-shielded-vulnerable-people-service-staging
          SECRET_KEY: ((svp-form/flask-secret-key-base-stg))
          NHS_OIDC_AUTHORITY_URL: https://auth.aos.signin.nhs.uk
          NHS_OIDC_LOGIN_CALLBACK_URL: https://gds-shielded-vulnerable-people-service-staging.london.cloudapps.digital/nhs-login-callback
          NHS_OIDC_REGISTRATION_CALLBACK_URL: https://gds-shielded-vulnerable-people-service-staging.london.cloudapps.digital/nhs-registration-callback
          AWS_ACCESS_KEY: ((svp-form/aws-access-key-id-stg))
          AWS_SECRET_ACCESS_KEY: ((svp-form/aws-secret-access-key-stg))
          AWS_SQS_QUEUE_URL: ((svp-form/aws-sqs-queue-url-stg))
          NHS_OIDC_LOGIN_PRIVATE_KEY: ((svp-form/nhs-login-private-key-stg))
          NHS_OIDC_CLIENT_ID: gds-svp
          SENTRY_DSN: ((svp-form/sentry-dns-stg))
          GA_TRACKING_ID: UA-43115970-1
          GA_CROSS_DOMAIN_ID: UA-145652997-7
          ENVIRONMENT: STAGING
          POSTCODE_TIER_OVERRIDE: ((svp-form/postcode-tier-override))
          SUBMISSION_TRACING_PEPPER: ((submission-tracing-pepper-stg))
        on_failure: *slack_alert_on_failure
        on_success: *slack_alert_on_fixed

  - name: smoke-test-staging
    serial: true
    plan:
      - get: git-master
        trigger: true
        passed: [deploy-to-staging]
      - task: smoke-test
        file: git-master/concourse/tasks/smoke-test.yml
        params:
          WEB_APP_BASE_URL: "https://gds-shielded-vulnerable-people-service-staging.london.cloudapps.digital"
          MESSAGE: "Checks that the application deployed to staging is not serving HTTP error codes"
          POSTCODE_TIER_OVERRIDE: ((svp-form/postcode-tier-override))
        on_failure: *slack_alert_on_failure
        on_success: *slack_alert_on_fixed

  - name: e2e-test-staging
    serial: true
    plan:
      - get: git-master
        trigger: true
        passed: [smoke-test-staging]
      - task: e2e-test
        file: git-master/concourse/tasks/e2e-test.yml
        attempts: 2
        params:
          CF_SPACE: "staging"
          ENVIRONMENT: "staging"
          WEB_APP_BASE_URL: "https://gds-shielded-vulnerable-people-service-staging.london.cloudapps.digital"
          MESSAGE: "Checks that the application deployed to staging is not serving HTTP error codes"
          POSTCODE_TIER_OVERRIDE: ((svp-form/postcode-tier-override))
          NHS_BASE_URL: https://access.aos.signin.nhs.uk
          NHS_EMAIL: ((svp-form/nhs-email-stg))
          NHS_OTP: ((svp-form/nhs-otp-stg))
          NHS_PASSWORD: ((svp-form/nhs-password-stg))
        on_failure: *slack_alert_on_failure
        on_success: *slack_alert_on_fixed

  - name: deploy-to-prod
    serial: true
    plan:
      - get: git-master
        trigger: false
        passed: [e2e-test-staging]
      - task: deploy-to-paas
        config:
        file: git-master/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          CF_SPACE: prod
          INSTANCES: 30
          CF_STARTUP_TIMEOUT: 15 # minutes
          HOSTNAME: gds-shielded-vulnerable-people-service-prod
          SECRET_KEY: ((svp-form/flask-secret-key-base-prod))
          NHS_OIDC_AUTHORITY_URL: https://auth.login.nhs.uk/
          NHS_OIDC_LOGIN_CALLBACK_URL: 	https://gds-shielded-vulnerable-people-service-prod.london.cloudapps.digital/nhs-login-callback
          NHS_OIDC_REGISTRATION_CALLBACK_URL: https://gds-shielded-vulnerable-people-service-prod.london.cloudapps.digital/nhs-registration-callback
          AWS_ACCESS_KEY: ((svp-form/aws-access-key-id-prod))
          AWS_SECRET_ACCESS_KEY: ((svp-form/aws-secret-access-key-prod))
          AWS_SQS_QUEUE_URL: ((svp-form/aws-sqs-queue-url-prod))
          NHS_OIDC_LOGIN_PRIVATE_KEY: ((svp-form/nhs-login-private-key-prod))
          NHS_OIDC_CLIENT_ID: gds-svp
          SENTRY_DSN: ((svp-form/sentry-dns-prod))
          GA_TRACKING_ID: UA-43115970-1
          GA_CROSS_DOMAIN_ID: UA-145652997-1
          ENVIRONMENT: PRODUCTION
          POSTCODE_TIER_OVERRIDE: ((svp-form/postcode-tier-override))
          SUBMISSION_TRACING_PEPPER: ((submission-tracing-pepper-prod))
        on_failure: *slack_alert_on_failure
        on_success: *slack_alert_on_fixed

  - name: smoke-test-prod
    serial: true
    plan:
      - get: git-master
        trigger: true
        passed: [deploy-to-prod]
      - task: smoke-test
        file: git-master/concourse/tasks/smoke-test.yml
        params:
          WEB_APP_BASE_URL: "https://gds-shielded-vulnerable-people-service-prod.london.cloudapps.digital"
          MESSAGE: "Checks that the application deployed to production is not serving HTTP error codes"
          POSTCODE_TIER_OVERRIDE: ((svp-form/postcode-tier-override))
        on_failure: *slack_alert_on_failure
        on_success: *slack_alert_on_success

  - name: continuous-smoke-test-staging
    plan:
      - get: every-2m
        trigger: true
      - get: git-master
        passed: [e2e-test-staging]
      - task: smoke-test
        file: git-master/concourse/tasks/smoke-test.yml
        params:
          WEB_APP_BASE_URL: "https://gds-shielded-vulnerable-people-service-staging.london.cloudapps.digital"
          MESSAGE: "Checks that the application deployed to staging is not serving HTTP error codes"
          POSTCODE_TIER_OVERRIDE: ((svp-form/postcode-tier-override))
        on_failure: *slack_alert_on_failure
        on_success: *slack_alert_on_fixed
      - task: cronitor-heartbeat
        timeout: 1m
        params:
          CRONITOR_URL: ((svp-form/cronitor-heartbeat-stg))
          CRONITOR_ENDPOINT: "/complete"
        file: git-master/concourse/tasks/cronitor.yml

  - name: continuous-smoke-test-prod
    plan:
      - get: every-2m
        trigger: true
      - get: git-master
        passed: [deploy-to-prod]
      - task: smoke-test
        file: git-master/concourse/tasks/smoke-test.yml
        params:
          WEB_APP_BASE_URL: "https://gds-shielded-vulnerable-people-service-prod.london.cloudapps.digital"
          MESSAGE: "Checks that the application deployed to production is not serving HTTP error codes"
          POSTCODE_TIER_OVERRIDE: ((svp-form/postcode-tier-override))
        on_failure:
          task: cronitor-fail
          file: git-master/concourse/tasks/cronitor.yml
          timeout: 1m
          params:
            CRONITOR_URL: ((svp-form/cronitor-heartbeat-prod))
            CRONITOR_ENDPOINT: "/fail"
          ensure: *slack_alert_on_failure
        on_success: *slack_alert_on_fixed
      - task: cronitor-heartbeat
        timeout: 1m
        params:
          CRONITOR_URL: ((svp-form/cronitor-heartbeat-prod))
          CRONITOR_ENDPOINT: "/complete"
        file: git-master/concourse/tasks/cronitor.yml

  - name: gatling-workflow-load-test-in-staging
    plan:
      - get: git-master
        passed: [e2e-test-staging]
      - get: trigger-at-1am
        trigger: true
      - task: gatling
        file: git-master/concourse/tasks/gatling-workflow-load-test.yml
        ensure:
          do:
            - task: get-aws-credentials
              file: git-master/concourse/tasks/get-gatling-tester-aws-creds.yml
              params:
                ACCOUNT_ID: 375282846305
                ENVIRONMENT: staging
                REGION: eu-west-2
                DURATION: 21600
            - task: upload-gatling-results-to-s3
              config:
                platform: linux
                image_resource:
                  type: registry-image
                  source:
                    repository: governmentpaas/awscli
                    tag: latest
                    username: ((docker_hub_username))
                    password: ((docker_hub_password))
                inputs:
                  - name: aws-credentials
                  - name: gatling-results
                run:
                  path: ash
                  args:
                    - -c
                    - |
                      set -euo pipefail
                      source aws-credentials/.env
                      DATE=$(date +%FT%T)
                      tar zvcf $DATE.tar.gz gatling-results 
                      aws s3 cp \
                        $DATE.tar.gz \
                        s3://gds-ons-covid-19-system-test-results-staging/gatling/workflow-load-tests/ \
            - task: clean-out-gatling-test-submissions-from-rds
              config:
                platform: linux
                image_resource:
                  type: registry-image
                  source:
                    repository: governmentpaas/awscli
                    tag: latest
                    username: ((docker_hub_username))
                    password: ((docker_hub_password))
                inputs:
                  - name: aws-credentials
                run:
                  path: ash
                  args:
                    - -c
                    - |
                      set -euo pipefail
                      source aws-credentials/.env
                      aws glue start-job-run \
                        --job-name "rds-clean-gatling-test-data"
    on_failure: *slack_alert_on_failure
    on_success: *slack_alert_on_fixed

  - name: run-daily-and-mi-workflows-in-staging
    plan:
      - get: git-master
        passed: [e2e-test-staging]
      - get: trigger-at-1am
        trigger: true
      - task: get-aws-credentials
        file: git-master/concourse/tasks/get-gatling-tester-aws-creds.yml
        params:
          ACCOUNT_ID: 375282846305
          ENVIRONMENT: staging
          REGION: eu-west-2
          DURATION: 21600
      - task: run-pipelines
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
              tag: latest
          inputs:
            - name: git-master
            - name: aws-credentials
          params:
            ENVIRONMENT: "staging"
            REGION: "eu-west-2"
          run:
            path: bash
            args:
              - -c
              - |
                set -euo pipefail
                echo "Installing system dependencies:"
                apt-get update
                apt-get upgrade -y
                apt-get install -y jq curl unzip git make python3 python3-pip

                echo "Installing libraries required for test:"
                source ../aws-credentials/.env
                make install

                echo "Running Python script to trigger workflow:"
                python3 scripts/trigger_glue_workflow_and_check_outcome.py --workflow_to_trigger cv-vulnerable-people-daily-wave-two-pipeline-staging \
                         --workflows_to_check cv-vulnerable-people-daily-wave-two-pipeline-staging,dw-etl-daily-pipeline-staging \
                         --timeout 10800 \
                         --wait_time 30
            dir: git-master
          on_failure: *slack_alert_on_failure
          on_success: *slack_alert_on_fixed

  - name: run-e2e-test-with-pipeline-validation-in-staging
    serial: true
    plan:
      - get: git-master
        passed: [e2e-test-staging]
      - get: trigger-at-6am
        trigger: true
      - task: webform-entry
        file: git-master/concourse/tasks/e2e-test-with-pipeline-validation-webform-entry.yml
        attempts: 1
        params:
          CF_SPACE: "staging"
          ENVIRONMENT: "staging"
          WEB_APP_BASE_URL: "https://gds-shielded-vulnerable-people-service-staging.london.cloudapps.digital"
          MESSAGE: "Checks that the application deployed to staging is not serving HTTP error codes"
          POSTCODE_TIER_OVERRIDE: ((svp-form/postcode-tier-override))
        on_failure: *slack_alert_on_failure
        on_success: *slack_alert_on_fixed
      - task: get-aws-credentials
        file: git-master/concourse/tasks/get-gatling-tester-aws-creds.yml
        params:
          ACCOUNT_ID: 375282846305
          ENVIRONMENT: staging
          REGION: eu-west-2
          DURATION: 21600
      - task: s3-validation
        file: git-master/concourse/tasks/e2e-test-with-pipeline-validation-s3-check.yml
        params:
          ENVIRONMENT: "staging"
          REGION: "eu-west-2"
          SALT: "1rjoBuOtDYaid83fYRJBFU5ouUi0nSueev2BhyoEhnw"
          POSTCODE_TIER_OVERRIDE: ((svp-form/postcode-tier-override))
        on_failure: *slack_alert_on_failure
        on_success: *slack_alert_on_fixed
